name: Build Quartz site on VPS and deploy to local web root

on:
  push:
    branches:  [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # This targets your VPS with the self-hosted runner
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git info

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Deploy to local web root
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r public/* /var/www/html/
